[project]
name = "review-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "scrapy>=2.13.3",
    "scrapy-playwright>=0.0.35",
    "playwright>=1.46.0",
]
